name: CreeperNotify
main: org.hopto.seed419.CreeperNotify
author: seed419
version: 0.0.6
description: Notifies players when a creeper has targeted them.
permissions:
    CreeperNotify.notify:
        description: Notifies player when a creeper has targeted them.